name: Security

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Sast-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Needed to upload SARIF results
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep
      run: semgrep scan --config "p/juice-shop" --sarif --output semgrep.sarif

    - name: Upload SARIF to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: semgrep.sarif

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag juice-shop:latest

    - name: Generate SBOM from Docker image
      uses: anchore/sbom-action@v0
      with:
        image: "juice-shop:latest"
        format: 'spdx-json'
        output-file: 'sbom.spdx.json'

    - name: Upload SBOM
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: 'sbom.spdx.json'

  Gitleaks-scan:
    name: Gitleaks (Secret)
    needs: Sast-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SecretScan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_ENABLE_SUMMARY: true
          GITLEAKS_REPORT_FORMAT: sarif
          GITLEAKS_REPORT_PATH: gitleaks-report.sarif
        continue-on-error: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'gitleaks-report.sarif'

      - name: Upload gitleaks artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gitleaks-report
          path: gitleaks-report.sarif